# Generated by Django 4.1.1 on 2022-09-19 13:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Order description', max_length=255, verbose_name='Order description')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(help_text='Count of item in order', validators=[django.core.validators.MinValueValidator(0, 'Item count can not be less than zero.')], verbose_name='Item count')),
                ('item', models.ForeignKey(help_text='Item Order pair', on_delete=django.db.models.deletion.CASCADE, related_name='item_order_pairs', to='payment.item', verbose_name='Item Order pair')),
                ('order', models.ForeignKey(help_text='Order Item pair', on_delete=django.db.models.deletion.CASCADE, related_name='order_item_pairs', to='payment.order', verbose_name='Order Item pair')),
            ],
            options={
                'verbose_name': 'OrderItem',
                'verbose_name_plural': 'OrderItems',
            },
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'item'), name='unique_pair_order_item'),
        ),
    ]
