# Generated by Django 4.1.1 on 2022-09-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_cart_order_session_id_delete_orderitem_cart_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Cart', 'verbose_name_plural': 'Carts'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterField(
            model_name='order',
            name='session_id',
            field=models.CharField(default=0, help_text='Session ID', max_length=32, unique=True, verbose_name='Session ID'),
            preserve_default=False,
        ),
    ]
