# Generated by Django 4.1.1 on 2022-09-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_cart_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.CharField(help_text='Order description', max_length=255, null=True, verbose_name='Order description'),
        ),
    ]
