# Generated by Django 4.1.1 on 2022-11-21 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_order_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('-id',), 'verbose_name': 'Cart', 'verbose_name_plural': 'Carts'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-id',), 'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-id',), 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='item',
            field=models.ForeignKey(help_text='Item Cart pair', on_delete=django.db.models.deletion.CASCADE, related_name='item_cart_pairs', to='payment.item', verbose_name='Item Cart pair'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='order',
            field=models.ForeignKey(help_text='Order Cart pair', on_delete=django.db.models.deletion.CASCADE, related_name='order_cart_pairs', to='payment.order', verbose_name='Order Cart pair'),
        ),
    ]
