# Generated by Django 4.2.7 on 2023-12-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payment', '0007_taxrate_alter_item_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxrate',
            options={
                'ordering': ('-id',),
                'verbose_name': 'Tax Rate',
                'verbose_name_plural': 'Tax Rates',
            },
        ),
        migrations.AddField(
            model_name='taxrate',
            name='stripe_tax_id',
            field=models.CharField(
                help_text='Stripe tax ID',
                max_length=64,
                null=True,
                verbose_name='stipe_tax_id',
            ),
        ),
    ]
