# Generated by Django 4.2.7 on 2023-12-01 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payment', '0008_alter_taxrate_options_taxrate_stripe_tax_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(
                decimal_places=2,
                help_text='Item price',
                max_digits=12,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message='Price cannot be negative.'
                    )
                ],
                verbose_name='Item price',
            ),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='stripe_tax_id',
            field=models.CharField(
                blank=True,
                help_text='Stripe tax ID',
                max_length=64,
                null=True,
                verbose_name='stipe_tax_id',
            ),
        ),
    ]
