# Generated by Django 4.2.7 on 2023-12-01 13:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('payment', '0010_cart_tax_rate_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='tax_rate_id',
            new_name='tax_rate',
        ),
    ]
